//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService211")]
    public interface IService211 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService211/Position", ReplyAction="http://tempuri.org/IService211/PositionResponse")]
        int Position();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService211/Position", ReplyAction="http://tempuri.org/IService211/PositionResponse")]
        System.Threading.Tasks.Task<int> PositionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService211Channel : Game.ServiceReference2.IService211, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service211Client : System.ServiceModel.ClientBase<Game.ServiceReference2.IService211>, Game.ServiceReference2.IService211 {
        
        public Service211Client() {
        }
        
        public Service211Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service211Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service211Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service211Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Position() {
            return base.Channel.Position();
        }
        
        public System.Threading.Tasks.Task<int> PositionAsync() {
            return base.Channel.PositionAsync();
        }
    }
}
